[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
node_sequential_6_1_dense_30_1_add_readvariableop_0 = { path = "../initializers/node_sequential_6_1_dense_30_1_add_readvariableop_0"} 
node_sequential_6_1_dense_30_1_cast_readvariableop_0 = { path = "../initializers/node_sequential_6_1_dense_30_1_cast_readvariableop_0"} 
node_sequential_6_1_dense_29_1_add_readvariableop_0 = { path = "../initializers/node_sequential_6_1_dense_29_1_add_readvariableop_0"} 
node_sequential_6_1_dense_29_1_cast_readvariableop_0 = { path = "../initializers/node_sequential_6_1_dense_29_1_cast_readvariableop_0"} 
node_sequential_6_1_dense_28_1_add_readvariableop_0 = { path = "../initializers/node_sequential_6_1_dense_28_1_add_readvariableop_0"} 
node_sequential_6_1_dense_28_1_cast_readvariableop_0 = { path = "../initializers/node_sequential_6_1_dense_28_1_cast_readvariableop_0"} 
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "57871a4" } 


[cairo]
enable-gas = false