[package]
name = "node_sequential_1_1_dense_1_1_cast_readvariableop_0"
version = "0.1.0"
edition = "2023_10"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "57871a4" } 


[cairo]
enable-gas = false